# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='银行卡')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('beizhu', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用内容')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goumairiqi', models.DateField(auto_now_add=True, verbose_name='购买日期')),
                ('qianpaipiaohao', models.CharField(max_length=100, verbose_name='前排票号')),
                ('piaohao', models.CharField(max_length=100, verbose_name='票号')),
                ('chupiaohang', models.CharField(max_length=100, verbose_name='出票行')),
                ('chupiaoriqi', models.DateField(verbose_name='出票日期')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('piaomianjiage', models.FloatField(default=0, verbose_name='票面价格')),
                ('gouruhuilv', models.FloatField(default=0, verbose_name='购入利率')),
                ('gourujiage', models.FloatField(default=0, verbose_name='购入价格')),
                ('gongyingshang', models.CharField(max_length=100, verbose_name='供应商')),
                ('maichuriqi', models.DateField(blank=True, null=True, verbose_name='卖出日期')),
                ('maichulilv', models.FloatField(default=0, verbose_name='卖出利率')),
                ('maichujiage', models.FloatField(default=0, verbose_name='卖出价格')),
                ('maichulirun', models.FloatField(default=0, verbose_name='卖出利润')),
                ('maipiaoren', models.CharField(max_length=100, verbose_name='买票人')),
                ('lirun', models.IntegerField(default=0, editable=False, verbose_name='利润')),
                ('t_status', models.IntegerField(choices=[(1, '购入未付款'), (2, '已付款'), (3, '卖出未收款'), (4, '已收款')], default=1, verbose_name='状态')),
                ('gourucard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_card', to='ticket.Card', verbose_name='购入卡')),
                ('maichucard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_card', to='ticket.Card', verbose_name='卖出卡')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('beizhu', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('yinhangka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_card', to='ticket.Card', verbose_name='银行卡')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='票据'),
        ),
    ]
