# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='maichulirun',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lirun',
            field=models.IntegerField(default=0, verbose_name='利润'),
        ),
    ]
