# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180408_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='maipiaoren',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='买票人'),
        ),
    ]
