# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180408_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gourucard',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='maichucard',
        ),
    ]
